version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: locadora-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: locadora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: locadora-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@locadora.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  webapi:
    build:
      context: .
      dockerfile: LocadoraWebAPI/Dockerfile
    container_name: locadora-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=locadora;Username=postgres;Password=1234
    depends_on:
      - postgres

volumes:
  pgdata: