// <auto-generated />
using System;
using Infrastructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20260504052315_AddDataCriacaoCarro")]
    partial class AddDataCriacaoCarro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Entities.Alocacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ALO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ALO_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CAR_DATA_CRIACAO");

                    b.Property<DateOnly?>("DataDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("ALO_DATA_DEVOLUCAO");

                    b.Property<DateOnly>("DataPrevistaDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("ALO_DATA_PREVISTA_DEVOLUCAO");

                    b.Property<DateOnly>("DataRetirada")
                        .HasColumnType("date")
                        .HasColumnName("ALO_DATA_RETIRADA");

                    b.Property<int>("IdCarro")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("ALO_STATUS");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("ALO_VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("IdCarro");

                    b.HasIndex("IdCliente");

                    b.ToTable("TB_ALOCACAO");
                });

            modelBuilder.Entity("Entities.Entities.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CAR_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("CAR_ANO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("CAR_ATIVO");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CAR_COR");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CAR_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CAR_DATA_CRIACAO");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean")
                        .HasColumnName("CAR_DISPONIVEL");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CAR_IMAGEM_URL");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CAR_MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CAR_MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("CAR_PLACA");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("TB_CARRO");
                });

            modelBuilder.Entity("Entities.Entities.CategoriaCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CAT_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("CAT_ATIVO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CAT_DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CAT_NOME");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric")
                        .HasColumnName("CAT_VALOR_DIARIA");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TB_CATEGORIA_CARRO");
                });

            modelBuilder.Entity("Entities.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CLI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("CLI_ATIVO");

                    b.Property<string>("CEP")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("CLI_CEP");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CLI_CPF");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CLI_CELULAR");

                    b.Property<string>("ComplementoEndereco")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("CLI_COMPLEMENTO_ENDERECO");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_DATA_ALTERACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLI_DATA_CRIACAO");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("CLI_DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CLI_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CLI_NOME");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_CLIENTE");
                });

            modelBuilder.Entity("Entities.Entities.Alocacao", b =>
                {
                    b.HasOne("Entities.Entities.Carro", "Carro")
                        .WithMany("Alocacoes")
                        .HasForeignKey("IdCarro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Cliente", "Cliente")
                        .WithMany("Alocacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Entities.Entities.Carro", b =>
                {
                    b.HasOne("Entities.Entities.CategoriaCarro", "Categoria")
                        .WithMany("Carros")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Entities.Entities.Carro", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("Entities.Entities.CategoriaCarro", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("Entities.Entities.Cliente", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
